[package]
name = "rotate-triangle"
version = "0.1.0"
authors = ["Rinwasyu <rinwakun@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glu-sys = "0.1.4"
glfw = "0.39.1"